name: CI workflow

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.cacheKeys.package }}
          restore-keys: ${{ runner.cacheKeys.package }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd testing/00-boilerplate
          npm i

      - name: Unit testing
        run: |
          cd testing/00-boilerplate
          npm test
      
      - name: e2e tests
        run: |
          cd testing/00-boilerplate
          npm test
