name: CI workflow

on:
  pull_request:
    paths:
      - 'testing/00-boilerplate/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run:  npm ci

      - name: Unit test
        run:  npm run test

      - name: e2e test
        run:  npm run test:e2e